from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="EnvironmentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("environment_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("environment_class", models.CharField(max_length=32)),
                ("provider", models.CharField(max_length=128)),
                ("cluster_provider", models.CharField(max_length=128)),
                ("host_provider", models.CharField(blank=True, max_length=128, null=True)),
                ("criticality", models.CharField(default="standard", max_length=64)),
                ("fingerprint", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "environment_id"]},
        ),
        migrations.CreateModel(
            name="OperationalProfileRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile_id", models.CharField(max_length=255, unique=True)),
                ("version", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("source_path", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["profile_id"]},
        ),
        migrations.CreateModel(
            name="AccessValidationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("validation_id", models.CharField(max_length=255, unique=True)),
                ("access_method_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("target_fingerprint", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("checked_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="access_validations", to="api.environmentrecord")),
            ],
            options={"ordering": ["-checked_at"]},
        ),
        migrations.CreateModel(
            name="EnvironmentSnapshotRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("source_type", models.CharField(max_length=32)),
                ("source_fingerprint", models.CharField(max_length=255)),
                ("captured_at", models.DateTimeField()),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="snapshots", to="api.environmentrecord")),
            ],
            options={"ordering": ["-captured_at"]},
        ),
        migrations.CreateModel(
            name="SnapshotEntityRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_id", models.CharField(max_length=512)),
                ("entity_type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("plane", models.CharField(max_length=64)),
                ("namespace", models.CharField(blank=True, max_length=255, null=True)),
                ("provider", models.CharField(blank=True, max_length=128, null=True)),
                ("labels", models.JSONField(default=dict)),
                ("desired_state", models.JSONField(default=dict)),
                ("observed_state", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entities", to="api.environmentsnapshotrecord")),
            ],
            options={"ordering": ["plane", "namespace", "entity_type", "name"]},
        ),
        migrations.CreateModel(
            name="SnapshotRelationshipRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relationship_id", models.CharField(max_length=768)),
                ("source_id", models.CharField(max_length=512)),
                ("target_id", models.CharField(max_length=512)),
                ("relationship_type", models.CharField(max_length=128)),
                ("confidence", models.FloatField(default=1.0)),
                ("provenance", models.CharField(max_length=255)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relationships", to="api.environmentsnapshotrecord")),
            ],
            options={"ordering": ["relationship_type", "relationship_id"]},
        ),
        migrations.CreateModel(
            name="ProfileAssessmentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_id", models.CharField(max_length=255, unique=True)),
                ("profile_id", models.CharField(max_length=255)),
                ("profile_version", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("payload", models.JSONField()),
                ("evaluated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="api.environmentsnapshotrecord")),
            ],
            options={"ordering": ["profile_id"]},
        ),
        migrations.AlterField(
            model_name="artifactrecord",
            name="run",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="api.scenariorunrecord"),
        ),
        migrations.AddField(model_name="artifactrecord", name="scope_type", field=models.CharField(default="simulation_run", max_length=64)),
        migrations.AddField(model_name="artifactrecord", name="scope_id", field=models.CharField(default="", max_length=255)),
        migrations.AddField(model_name="artifactrecord", name="metadata", field=models.JSONField(default=dict)),
        migrations.AddConstraint(model_name="snapshotentityrecord", constraint=models.UniqueConstraint(fields=("snapshot", "entity_id"), name="unique_snapshot_entity")),
        migrations.AddConstraint(model_name="snapshotrelationshiprecord", constraint=models.UniqueConstraint(fields=("snapshot", "relationship_id"), name="unique_snapshot_relationship")),
        migrations.AddConstraint(model_name="profileassessmentrecord", constraint=models.UniqueConstraint(fields=("snapshot", "profile_id"), name="unique_snapshot_profile_assessment")),
        migrations.AddIndex(model_name="environmentrecord", index=models.Index(fields=["environment_class", "active"], name="api_environ_environ_4a9ea7_idx")),
        migrations.AddIndex(model_name="accessvalidationrecord", index=models.Index(fields=["environment", "checked_at"], name="api_accessv_environ_91e5d0_idx")),
        migrations.AddIndex(model_name="environmentsnapshotrecord", index=models.Index(fields=["environment", "captured_at"], name="api_environ_environ_4c8818_idx")),
        migrations.AddIndex(model_name="environmentsnapshotrecord", index=models.Index(fields=["status", "captured_at"], name="api_environ_status_c04f4a_idx")),
        migrations.AddIndex(model_name="snapshotentityrecord", index=models.Index(fields=["snapshot", "entity_type"], name="api_snapsho_snapsho_f68543_idx")),
        migrations.AddIndex(model_name="snapshotentityrecord", index=models.Index(fields=["snapshot", "namespace"], name="api_snapsho_snapsho_584896_idx")),
        migrations.AddIndex(model_name="snapshotentityrecord", index=models.Index(fields=["snapshot", "plane"], name="api_snapsho_snapsho_5ab5a1_idx")),
        migrations.AddIndex(model_name="snapshotrelationshiprecord", index=models.Index(fields=["snapshot", "source_id"], name="api_snapsho_snapsho_d79c7e_idx")),
        migrations.AddIndex(model_name="snapshotrelationshiprecord", index=models.Index(fields=["snapshot", "target_id"], name="api_snapsho_snapsho_e3e71d_idx")),
        migrations.AddIndex(model_name="snapshotrelationshiprecord", index=models.Index(fields=["snapshot", "relationship_type"], name="api_snapsho_snapsho_55e753_idx")),
        migrations.AddIndex(model_name="profileassessmentrecord", index=models.Index(fields=["profile_id", "status"], name="api_profile_profile_b7bfe7_idx")),
        migrations.AddIndex(model_name="artifactrecord", index=models.Index(fields=["scope_type", "scope_id"], name="api_artifac_scope_t_96af67_idx")),
    ]
