from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("api", "0005_release_05_knowledge_packs")]

    operations = [
        migrations.CreateModel(
            name="OrganizationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "organization_id"]},
        ),
        migrations.CreateModel(
            name="WorkspaceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workspace_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspaces", to="api.organizationrecord")),
            ],
            options={"ordering": ["organization", "name", "workspace_id"]},
        ),
        migrations.AddConstraint(
            model_name="workspacerecord",
            constraint=models.UniqueConstraint(fields=("organization", "slug"), name="unique_workspace_slug_per_org"),
        ),
        migrations.AddField(
            model_name="scenariorunrecord",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scenario_runs", to="api.organizationrecord"),
        ),
        migrations.AddField(
            model_name="scenariorunrecord",
            name="workspace",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="scenario_runs", to="api.workspacerecord"),
        ),
        migrations.AddField(
            model_name="artifactrecord",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="api.organizationrecord"),
        ),
        migrations.AddField(
            model_name="artifactrecord",
            name="workspace",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="api.workspacerecord"),
        ),
        migrations.AddIndex(
            model_name="scenariorunrecord",
            index=models.Index(fields=["workspace", "created_at"], name="api_scenari_workspa_10a001_idx"),
        ),
        migrations.AddIndex(
            model_name="artifactrecord",
            index=models.Index(fields=["workspace", "created_at"], name="api_artifac_workspa_10a002_idx"),
        ),
        migrations.AddField(
            model_name="environmentrecord",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="environments", to="api.organizationrecord"),
        ),
        migrations.AddField(
            model_name="environmentrecord",
            name="workspace",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="environments", to="api.workspacerecord"),
        ),
        migrations.CreateModel(
            name="RoleGrantRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grant_id", models.CharField(max_length=255, unique=True)),
                ("principal_id", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=32)),
                ("scope_type", models.CharField(max_length=32)),
                ("scope_id", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField()),
                ("granted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["principal_id", "scope_type", "scope_id", "role"],
                "indexes": [
                    models.Index(fields=["principal_id", "active"], name="api_rolegra_princip_341ece_idx"),
                    models.Index(fields=["scope_type", "scope_id", "active"], name="api_rolegra_scope_t_9fc326_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FleetRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fleet_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("max_parallel_operations", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fleets", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fleets", to="api.workspacerecord")),
            ],
            options={"ordering": ["workspace", "name", "fleet_id"]},
        ),
        migrations.CreateModel(
            name="FleetMembershipRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criticality", models.CharField(default="standard", max_length=64)),
                ("failure_domain", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fleet_memberships", to="api.environmentrecord")),
                ("fleet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="api.fleetrecord")),
            ],
            options={"ordering": ["fleet", "environment"]},
        ),
        migrations.AddConstraint(
            model_name="fleetmembershiprecord",
            constraint=models.UniqueConstraint(fields=("fleet", "environment"), name="unique_fleet_environment"),
        ),
        migrations.CreateModel(
            name="FleetDependencyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dependency_id", models.CharField(max_length=255, unique=True)),
                ("relationship_type", models.CharField(max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("fleet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dependencies", to="api.fleetrecord")),
                ("source_environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fleet_dependencies_out", to="api.environmentrecord")),
                ("target_environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fleet_dependencies_in", to="api.environmentrecord")),
            ],
            options={"ordering": ["fleet", "dependency_id"]},
        ),
        migrations.CreateModel(
            name="FleetAssessmentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("generated_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fleet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="api.fleetrecord")),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["fleet", "generated_at"], name="api_fleetass_fleet_i_893e22_idx"),
                    models.Index(fields=["status", "generated_at"], name="api_fleetass_status_72254e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutorAgentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agent_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("capabilities", models.JSONField(default=list)),
                ("supported_executor_ids", models.JSONField(default=list)),
                ("environment_ids", models.JSONField(default=list)),
                ("max_concurrency", models.PositiveIntegerField(default=1)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("public_identity", models.CharField(blank=True, max_length=512, null=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executor_agents", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executor_agents", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "name", "agent_id"],
                "indexes": [
                    models.Index(fields=["workspace", "status"], name="api_executor_workspa_67daef_idx"),
                    models.Index(fields=["status", "last_heartbeat_at"], name="api_executor_status_7ff252_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutorHeartbeatRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heartbeat_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="heartbeats", to="api.executoragentrecord")),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [models.Index(fields=["agent", "occurred_at"], name="api_executor_agent_i_c49d95_idx")],
            },
        ),
        migrations.CreateModel(
            name="ExecutionTaskRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("action_id", models.CharField(max_length=255)),
                ("action_type_id", models.CharField(max_length=255)),
                ("executor_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("priority", models.IntegerField(default=0)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("assigned_agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_tasks", to="api.executoragentrecord")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_tasks", to="api.environmentrecord")),
                ("operation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_tasks", to="api.operationrecord")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_tasks", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="execution_tasks", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "status", "priority"], name="api_execution_workspa_e06e33_idx"),
                    models.Index(fields=["operation", "action_id"], name="api_execution_operati_f0e272_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskLeaseRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lease_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("nonce_hash", models.CharField(max_length=64)),
                ("acquired_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("heartbeat_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("agent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_leases", to="api.executoragentrecord")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leases", to="api.executiontaskrecord")),
            ],
            options={
                "ordering": ["-acquired_at"],
                "indexes": [
                    models.Index(fields=["task", "status"], name="api_tasklea_task_id_2d8cce_idx"),
                    models.Index(fields=["agent", "status", "expires_at"], name="api_tasklea_agent_i_7c4d15_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEventRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveBigIntegerField()),
                ("principal_id", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("resource_type", models.CharField(max_length=128)),
                ("resource_id", models.CharField(max_length=512)),
                ("outcome", models.CharField(max_length=64)),
                ("previous_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("event_hash", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "sequence"],
                "indexes": [
                    models.Index(fields=["workspace", "occurred_at"], name="api_auditev_workspa_699264_idx"),
                    models.Index(fields=["principal_id", "occurred_at"], name="api_auditev_princip_d8125a_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="auditeventrecord",
            constraint=models.UniqueConstraint(fields=("workspace", "sequence"), name="unique_workspace_audit_sequence"),
        ),
        migrations.CreateModel(
            name="RateLimitRuleRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_id", models.CharField(max_length=255, unique=True)),
                ("operation", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rate_limit_rules", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rate_limit_rules", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "operation", "rule_id"],
                "indexes": [models.Index(fields=["workspace", "operation", "enabled"], name="api_ratelim_ws_op_en_idx")],
            },
        ),
        migrations.CreateModel(
            name="ConcurrencyRuleRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_id", models.CharField(max_length=255, unique=True)),
                ("operation_type", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="concurrency_rules", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="concurrency_rules", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "operation_type", "rule_id"],
                "indexes": [models.Index(fields=["workspace", "operation_type", "enabled"], name="api_concurr_ws_op_en_idx")],
            },
        ),
        migrations.CreateModel(
            name="GovernanceUsageRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("usage_id", models.CharField(max_length=255, unique=True)),
                ("operation", models.CharField(max_length=255)),
                ("target_id", models.CharField(blank=True, max_length=512, null=True)),
                ("decision_id", models.CharField(max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("terminal", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="governance_usage", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["workspace", "operation", "occurred_at"], name="api_govuse_ws_op_at_idx"),
                    models.Index(fields=["workspace", "operation", "target_id", "terminal"], name="api_govuse_ws_op_tgt_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindowRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_id", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_windows", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_windows", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "window_id"],
                "indexes": [models.Index(fields=["workspace", "enabled"], name="api_maint_ws_enabled_idx")],
            },
        ),
        migrations.CreateModel(
            name="ScheduledOperationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("schedule_id", models.CharField(max_length=255, unique=True)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.CharField(max_length=255)),
                ("operation_type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                ("fleet", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="schedule_requests", to="api.fleetrecord")),
                ("maintenance_window", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="scheduled_operations", to="api.maintenancewindowrecord")),
                ("operation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="schedule_requests", to="api.operationrecord")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scheduled_operations", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scheduled_operations", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["workspace", "status", "not_before", "created_at"],
                "indexes": [
                    models.Index(fields=["workspace", "status", "not_before"], name="api_sched_ws_status_nb_idx"),
                    models.Index(fields=["workspace", "target_type", "target_id", "status"], name="api_sched_ws_target_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("policy_id", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retention_policies", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retention_policies", to="api.workspacerecord")),
            ],
            options={"ordering": ["workspace", "policy_id"]},
        ),
        migrations.CreateModel(
            name="PackSignatureRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signature_id", models.CharField(max_length=255, unique=True)),
                ("scheme", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=255)),
                ("signer", models.CharField(max_length=255)),
                ("signature", models.TextField()),
                ("manifest_hash", models.CharField(max_length=64)),
                ("signed_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="signatures", to="api.knowledgepackrecord")),
            ],
            options={
                "ordering": ["pack", "-signed_at"],
                "indexes": [models.Index(fields=["pack", "key_id", "signed_at"], name="api_packsign_pack_id_49dfe9_idx")],
            },
        ),
        migrations.CreateModel(
            name="PackTrustPolicyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("policy_id", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pack_trust_policies", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pack_trust_policies", to="api.workspacerecord")),
            ],
            options={"ordering": ["workspace", "policy_id"]},
        ),
        migrations.CreateModel(
            name="SecretReferenceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret_ref_id", models.CharField(max_length=255, unique=True)),
                ("provider", models.CharField(max_length=64)),
                ("locator_redacted", models.CharField(max_length=512)),
                ("purpose", models.TextField(blank=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secret_references", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secret_references", to="api.workspacerecord")),
            ],
            options={"ordering": ["workspace", "secret_ref_id"]},
        ),
        migrations.CreateModel(
            name="PlatformBackupRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("backup_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("manifest_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_backups", to="api.organizationrecord")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_backups", to="api.workspacerecord")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["workspace", "status", "created_at"], name="api_platform_workspa_64ea72_idx")],
            },
        ),
    ]
