from django.urls import path

from .views import (
    ArtifactDetailView,
    ActionCatalogView,
    ArtifactListView,
    CompositionCompileView,
    CompositionRunView,
    DiagnosticCatalogView,
    DiagnosisCoverageView,
    EnvironmentAccessValidationView,
    EnvironmentDetailView,
    EnvironmentListView,
    EnvironmentSnapshotListView,
    ExecutionPolicyListView,
    IncidentCertificateView,
    IncidentDetailView,
    IncidentListView,
    IncidentProbeRunView,
    LifecycleProfileDetailView,
    LifecycleProfileListView,
    OperationalProfileDetailView,
    OperationalProfileListView,
    OperationApprovalView,
    OperationCancelView,
    OperationCertificateView,
    OperationDetailView,
    OperationListCreateView,
    OperationPauseView,
    OperationResumeView,
    OperationRollbackView,
    OperationRunView as GuardedOperationRunView,
    RegistryView,
    ScenarioCompileView,
    ScenarioDiagnoseView,
    ScenarioFamilyDetailView,
    ScenarioFamilyListView,
    ScenarioRunDetailView,
    ScenarioRunListView,
    ScenarioRunView,
    SchemaView,
    SnapshotDetailView,
    SnapshotDiffView,
    SnapshotFixtureExportView,
    SnapshotHealthView,
    SnapshotLifecyclePlanView,
    SnapshotIncidentCreateView,
    SnapshotTopologyView,
    SystemStatusView,
)

urlpatterns = [
    path("system/status", SystemStatusView.as_view(), name="system-status"),
    path("registry", RegistryView.as_view(), name="registry"),
    path("schemas/<str:schema_name>", SchemaView.as_view(), name="schema-detail"),
    path("operational-profiles", OperationalProfileListView.as_view(), name="operational-profile-list"),
    path("action-catalog", ActionCatalogView.as_view(), name="action-catalog"),
    path("lifecycle-profiles", LifecycleProfileListView.as_view(), name="lifecycle-profile-list"),
    path("lifecycle-profiles/<path:profile_id>", LifecycleProfileDetailView.as_view(), name="lifecycle-profile-detail"),
    path("execution-policies", ExecutionPolicyListView.as_view(), name="execution-policy-list"),
    path("operational-profiles/<path:profile_id>", OperationalProfileDetailView.as_view(), name="operational-profile-detail"),
    path("environments", EnvironmentListView.as_view(), name="environment-list"),
    path("environments/<path:environment_id>", EnvironmentDetailView.as_view(), name="environment-detail"),
    path("environments/<path:environment_id>/validate", EnvironmentAccessValidationView.as_view(), name="environment-validate"),
    path("environments/<path:environment_id>/snapshots", EnvironmentSnapshotListView.as_view(), name="environment-snapshot-list"),
    path("snapshots/<path:snapshot_id>", SnapshotDetailView.as_view(), name="snapshot-detail"),
    path("snapshots/<path:snapshot_id>/incidents", SnapshotIncidentCreateView.as_view(), name="snapshot-incident-create"),
    path("snapshots/<path:snapshot_id>/topology", SnapshotTopologyView.as_view(), name="snapshot-topology"),
    path("snapshots/<path:snapshot_id>/diff", SnapshotDiffView.as_view(), name="snapshot-diff"),
    path("snapshots/<path:snapshot_id>/health", SnapshotHealthView.as_view(), name="snapshot-health"),
    path("snapshots/<path:snapshot_id>/lifecycle/plan", SnapshotLifecyclePlanView.as_view(), name="snapshot-lifecycle-plan"),
    path("snapshots/<path:snapshot_id>/export", SnapshotFixtureExportView.as_view(), name="snapshot-export"),
    path("diagnostic-catalog", DiagnosticCatalogView.as_view(), name="diagnostic-catalog"),
    path("diagnosis/coverage", DiagnosisCoverageView.as_view(), name="diagnosis-coverage"),
    path("incidents", IncidentListView.as_view(), name="incident-list"),
    path("operations", OperationListCreateView.as_view(), name="operation-list-create"),
    path("operations/<str:operation_id>", OperationDetailView.as_view(), name="operation-detail"),
    path("operations/<str:operation_id>/approvals", OperationApprovalView.as_view(), name="operation-approval"),
    path("operations/<str:operation_id>/run", GuardedOperationRunView.as_view(), name="operation-run"),
    path("operations/<str:operation_id>/pause", OperationPauseView.as_view(), name="operation-pause"),
    path("operations/<str:operation_id>/cancel", OperationCancelView.as_view(), name="operation-cancel"),
    path("operations/<str:operation_id>/resume", OperationResumeView.as_view(), name="operation-resume"),
    path("operations/<str:operation_id>/rollback", OperationRollbackView.as_view(), name="operation-rollback"),
    path("operations/<str:operation_id>/certificate", OperationCertificateView.as_view(), name="operation-certificate"),
    path("incidents/<str:incident_id>", IncidentDetailView.as_view(), name="incident-detail"),
    path("incidents/<str:incident_id>/certificate", IncidentCertificateView.as_view(), name="incident-certificate"),
    path("incidents/<str:incident_id>/probes/<str:probe_id>/run", IncidentProbeRunView.as_view(), name="incident-probe-run"),
    path("scenario-families", ScenarioFamilyListView.as_view(), name="scenario-family-list"),
    path("scenario-families/<path:family_id>", ScenarioFamilyDetailView.as_view(), name="scenario-family-detail"),
    path("scenarios/compile", ScenarioCompileView.as_view(), name="scenario-compile"),
    path("scenarios/diagnose", ScenarioDiagnoseView.as_view(), name="scenario-diagnose"),
    path("scenarios/run", ScenarioRunView.as_view(), name="scenario-run"),
    path("compositions/compile", CompositionCompileView.as_view(), name="composition-compile"),
    path("compositions/run", CompositionRunView.as_view(), name="composition-run"),
    path("artifacts", ArtifactListView.as_view(), name="artifact-list"),
    path("artifacts/<str:artifact_id>", ArtifactDetailView.as_view(), name="artifact-detail"),
    path("runs", ScenarioRunListView.as_view(), name="run-list"),
    path("runs/<str:run_id>", ScenarioRunDetailView.as_view(), name="run-detail"),
]
