from django.urls import path

from .views import (
    ArtifactDetailView,
    ArtifactListView,
    CompositionCompileView,
    CompositionRunView,
    EnvironmentAccessValidationView,
    EnvironmentDetailView,
    EnvironmentListView,
    EnvironmentSnapshotListView,
    OperationalProfileDetailView,
    OperationalProfileListView,
    RegistryView,
    ScenarioCompileView,
    ScenarioFamilyDetailView,
    ScenarioFamilyListView,
    ScenarioRunDetailView,
    ScenarioRunListView,
    ScenarioRunView,
    SchemaView,
    SnapshotDetailView,
    SnapshotDiffView,
    SnapshotFixtureExportView,
    SnapshotHealthView,
    SnapshotTopologyView,
    SystemStatusView,
)

urlpatterns = [
    path("system/status", SystemStatusView.as_view(), name="system-status"),
    path("registry", RegistryView.as_view(), name="registry"),
    path("schemas/<str:schema_name>", SchemaView.as_view(), name="schema-detail"),
    path("operational-profiles", OperationalProfileListView.as_view(), name="operational-profile-list"),
    path("operational-profiles/<path:profile_id>", OperationalProfileDetailView.as_view(), name="operational-profile-detail"),
    path("environments", EnvironmentListView.as_view(), name="environment-list"),
    path("environments/<path:environment_id>", EnvironmentDetailView.as_view(), name="environment-detail"),
    path("environments/<path:environment_id>/validate", EnvironmentAccessValidationView.as_view(), name="environment-validate"),
    path("environments/<path:environment_id>/snapshots", EnvironmentSnapshotListView.as_view(), name="environment-snapshot-list"),
    path("snapshots/<path:snapshot_id>", SnapshotDetailView.as_view(), name="snapshot-detail"),
    path("snapshots/<path:snapshot_id>/topology", SnapshotTopologyView.as_view(), name="snapshot-topology"),
    path("snapshots/<path:snapshot_id>/diff", SnapshotDiffView.as_view(), name="snapshot-diff"),
    path("snapshots/<path:snapshot_id>/health", SnapshotHealthView.as_view(), name="snapshot-health"),
    path("snapshots/<path:snapshot_id>/export", SnapshotFixtureExportView.as_view(), name="snapshot-export"),
    path("scenario-families", ScenarioFamilyListView.as_view(), name="scenario-family-list"),
    path("scenario-families/<path:family_id>", ScenarioFamilyDetailView.as_view(), name="scenario-family-detail"),
    path("scenarios/compile", ScenarioCompileView.as_view(), name="scenario-compile"),
    path("scenarios/run", ScenarioRunView.as_view(), name="scenario-run"),
    path("compositions/compile", CompositionCompileView.as_view(), name="composition-compile"),
    path("compositions/run", CompositionRunView.as_view(), name="composition-run"),
    path("artifacts", ArtifactListView.as_view(), name="artifact-list"),
    path("artifacts/<str:artifact_id>", ArtifactDetailView.as_view(), name="artifact-detail"),
    path("runs", ScenarioRunListView.as_view(), name="run-list"),
    path("runs/<str:run_id>", ScenarioRunDetailView.as_view(), name="run-detail"),
]
