import { useEffect, useState } from "react";
import { api } from "../../api/client";
import { Badge } from "../../components/Badge";
import { JsonInspector } from "../../components/JsonInspector";
import type { AuditChainVerification, AuditEvent, ConcurrencyRule, ControlPlaneBackupManifest, ExecutorAgentDefinition, RateLimitRule, RetentionPlan, RetentionPolicy, RoleGrant, UpgradeReadinessReport, MaintenanceWindow, ScheduledOperation } from "../../types";

type Tab = "access" | "executors" | "limits" | "schedules" | "audit" | "retention" | "recovery";

export function GovernanceWorkbench() {
  const [tab, setTab] = useState<Tab>("access");
  const [grants, setGrants] = useState<RoleGrant[]>([]);
  const [agents, setAgents] = useState<ExecutorAgentDefinition[]>([]);
  const [events, setEvents] = useState<AuditEvent[]>([]);
  const [verification, setVerification] = useState<AuditChainVerification | null>(null);
  const [rateLimits, setRateLimits] = useState<RateLimitRule[]>([]);
  const [concurrencyLimits, setConcurrencyLimits] = useState<ConcurrencyRule[]>([]);
  const [policies, setPolicies] = useState<RetentionPolicy[]>([]);
  const [windows, setWindows] = useState<MaintenanceWindow[]>([]);
  const [schedules, setSchedules] = useState<ScheduledOperation[]>([]);
  const [retentionPlan, setRetentionPlan] = useState<RetentionPlan | null>(null);
  const [backups, setBackups] = useState<ControlPlaneBackupManifest[]>([]);
  const [readiness, setReadiness] = useState<UpgradeReadinessReport | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const refresh = async () => {
    try {
      const [nextGrants, nextAgents, nextRateLimits, nextConcurrencyLimits, nextWindows, nextSchedules, nextEvents, nextPolicies, nextBackups] = await Promise.all([api.roleGrants(), api.executorAgents(), api.rateLimits(), api.concurrencyLimits(), api.maintenanceWindows(), api.scheduledOperations(), api.auditEvents(), api.retentionPolicies(), api.platformBackups()]);
      setGrants(nextGrants); setAgents(nextAgents); setRateLimits(nextRateLimits); setConcurrencyLimits(nextConcurrencyLimits); setWindows(nextWindows); setSchedules(nextSchedules); setEvents(nextEvents); setPolicies(nextPolicies); setBackups(nextBackups);
    } catch (reason) { setError((reason as Error).message); }
  };
  useEffect(() => { void refresh(); }, []);

  const verify = async () => { setBusy("verify"); try { setVerification(await api.verifyAudit()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };
  const planRetention = async () => { if (!policies[0]) return; setBusy("retention"); try { setRetentionPlan(await api.planRetention(policies[0].policy_id)); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };
  const backup = async () => { setBusy("backup"); try { await api.createPlatformBackup(); setBackups(await api.platformBackups()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };
  const checkReadiness = async () => { setBusy("readiness"); try { setReadiness(await api.platformReadiness()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };
  const evaluateSchedule = async (scheduleId: string) => { setBusy(scheduleId); try { await api.evaluateScheduledOperation(scheduleId); setSchedules(await api.scheduledOperations()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };
  const materializeSchedule = async (scheduleId: string) => { setBusy(scheduleId); try { await api.materializeScheduledOperation(scheduleId); setSchedules(await api.scheduledOperations()); } catch (reason) { setError((reason as Error).message); } finally { setBusy(null); } };

  return <main className="governance-workbench">
    <header className="governance-header"><div><small>Release 1.0</small><h1>Governance & Recovery</h1><p>Hierarchical access, distributed executors, tamper-evident audit, retention, and control-plane recoverability.</p></div><div className="header-status"><Badge tone="accent">{grants.length} grants</Badge><Badge tone={agents.some((agent) => agent.status === "online") ? "positive" : "warning"}>{agents.filter((agent) => agent.status === "online").length} agents online</Badge></div></header>
    <nav className="workspace-tabs">{(["access","executors","limits","schedules","audit","retention","recovery"] as const).map((value) => <button type="button" key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{value}</button>)}</nav>
    {error && <div className="error-banner">{error}</div>}
    {tab === "access" && <section className="panel"><div className="section-heading"><h2>Hierarchical role grants</h2><Badge tone="accent">{grants.length}</Badge></div><div className="governance-list">{grants.map((grant) => <article key={grant.grant_id}><div><strong>{grant.principal_id}</strong><small>{grant.scope_type}:{grant.scope_id}</small></div><Badge tone={grant.active ? "positive" : "neutral"}>{grant.role}</Badge><code>{grant.capabilities.join(", ") || "role defaults"}</code></article>)}</div></section>}
    {tab === "executors" && <section className="panel"><div className="section-heading"><h2>Distributed executor agents</h2><Badge tone="accent">{agents.length}</Badge></div><div className="executor-grid">{agents.map((agent) => <article key={agent.agent_id}><header><div><strong>{agent.name}</strong><small>{agent.agent_id}</small></div><Badge tone={agent.status === "online" ? "positive" : agent.status === "degraded" ? "warning" : "neutral"}>{agent.status}</Badge></header><div className="metric-grid compact"><div><small>Capacity</small><strong>{agent.max_concurrency}</strong></div><div><small>Environments</small><strong>{agent.environment_ids.length}</strong></div><div><small>Capabilities</small><strong>{agent.capabilities.length}</strong></div><div><small>Executors</small><strong>{agent.supported_executor_ids.length}</strong></div></div><small>{agent.last_heartbeat_at_iso ?? "No heartbeat recorded"}</small></article>)}</div></section>}
    {tab === "limits" && <section className="workspace-grid"><section className="panel"><div className="section-heading"><div><h2>Rate limits</h2><small>Durable workspace request budgets</small></div><Badge tone="accent">{rateLimits.length}</Badge></div><div className="governance-list">{rateLimits.map((rule) => <article key={rule.rule_id}><div><strong>{rule.operation}</strong><small>{rule.rule_id} · {rule.scope_type}:{rule.scope_id}</small></div><Badge tone={rule.enabled ? "positive" : "neutral"}>{rule.enabled ? "enabled" : "disabled"}</Badge><code>{rule.limit} + {rule.burst} / {rule.window_seconds}s</code></article>)}</div></section><section className="panel"><div className="section-heading"><div><h2>Concurrency limits</h2><small>Active-operation and target-serialization guards</small></div><Badge tone="accent">{concurrencyLimits.length}</Badge></div><div className="governance-list">{concurrencyLimits.map((rule) => <article key={rule.rule_id}><div><strong>{rule.operation_type}</strong><small>{rule.rule_id} · {rule.scope_type}:{rule.scope_id}</small></div><Badge tone={rule.enabled ? "positive" : "neutral"}>{rule.enabled ? "enabled" : "disabled"}</Badge><code>max {rule.maximum_active}{rule.serialize_by_target ? " · serialized by target" : ""}</code></article>)}</div></section></section>}
    {tab === "schedules" && <section className="workspace-grid"><section className="panel"><div className="section-heading"><div><h2>Maintenance windows</h2><small>Timezone-aware eligibility gates; disabled windows deny materialization.</small></div><Badge tone="accent">{windows.length}</Badge></div><div className="governance-list">{windows.map((window) => <article key={window.window_id}><div><strong>{window.name}</strong><small>{window.timezone} · days {window.days_of_week.join(",")}</small></div><Badge tone={window.enabled ? "positive" : "neutral"}>{window.enabled ? "enabled" : "disabled"}</Badge><code>{window.start_local_time} · {window.duration_minutes}m</code></article>)}</div></section><section className="panel"><div className="section-heading"><div><h2>Scheduled operations</h2><small>The scheduler only materializes governed operations or fleet plans.</small></div><Badge tone="accent">{schedules.length}</Badge></div><div className="governance-list">{schedules.map((item) => <article key={item.schedule_id}><div><strong>{item.operation_type}</strong><small>{item.target_type}:{item.target_id} · {item.schedule_id}</small></div><Badge tone={item.status === "ready" || item.status === "materialized" ? "positive" : item.status === "blocked" || item.status === "expired" ? "negative" : "warning"}>{item.status}</Badge><code>{item.maintenance_window_id ?? "no window"}</code><div className="inline-actions"><button type="button" className="button" disabled={busy !== null || ["materialized","cancelled","expired"].includes(item.status)} onClick={() => evaluateSchedule(item.schedule_id)}>Evaluate</button><button type="button" className="button primary" disabled={busy !== null || item.status !== "ready"} onClick={() => materializeSchedule(item.schedule_id)}>Materialize</button></div></article>)}</div></section></section>}
    {tab === "audit" && <section className="panel"><div className="section-heading"><div><h2>Tamper-evident audit chain</h2><small>{events.length} persisted events</small></div><button type="button" className="button" disabled={busy !== null} onClick={verify}>{busy === "verify" ? "Verifying…" : "Verify chain"}</button></div>{verification && <div className="viz-callout"><strong>{verification.valid ? "Audit chain verified" : "Audit chain invalid"}</strong><p>{verification.event_count} events · head {verification.head_hash ?? "none"}</p></div>}<div className="audit-list">{events.slice(-30).reverse().map((event) => <article key={event.event_id}><span className="audit-sequence">{event.sequence}</span><div><strong>{event.action}</strong><small>{event.principal_id} · {event.resource_type}:{event.resource_id}</small></div><Badge tone={event.outcome.startsWith("2") || event.outcome === "success" ? "positive" : "warning"}>{event.outcome}</Badge></article>)}</div></section>}
    {tab === "retention" && <section className="panel"><div className="section-heading"><div><h2>Retention governance</h2><small>Certificate and legal-hold-aware cleanup planning</small></div><button type="button" className="button" disabled={!policies[0] || busy !== null} onClick={planRetention}>{busy === "retention" ? "Planning…" : "Dry-run retention"}</button></div><div className="governance-list">{policies.map((policy) => <article key={policy.policy_id}><div><strong>{policy.policy_id}</strong><small>{policy.scope_type}:{policy.scope_id}</small></div><Badge tone={policy.enabled ? "positive" : "neutral"}>{policy.enabled ? "enabled" : "disabled"}</Badge><code>{policy.artifact_retention_days}d artifacts · {policy.audit_retention_days}d audit</code></article>)}</div>{retentionPlan && <div className="retention-summary"><div className="metric-grid"><div><small>Candidates</small><strong>{retentionPlan.candidates.length}</strong></div><div><small>Eligible</small><strong>{retentionPlan.eligible_candidate_ids.length}</strong></div><div><small>Protected</small><strong>{retentionPlan.protected_candidate_ids.length}</strong></div><div><small>Reclaimable</small><strong>{retentionPlan.total_reclaimable_bytes}</strong></div></div><JsonInspector value={retentionPlan} /></div>}</section>}
    {tab === "recovery" && <section className="workspace-grid"><section className="panel"><div className="section-heading"><div><h2>Control-plane backups</h2><small>Database, artifact store, configuration, pack resolution, and audit head</small></div><button type="button" className="button primary" disabled={busy !== null} onClick={backup}>{busy === "backup" ? "Capturing…" : "Create manifest"}</button></div><div className="governance-list">{backups.map((item) => <article key={item.backup_id}><div><strong>{item.backup_id}</strong><small>{item.created_at_iso}</small></div><Badge tone={item.status === "verified" ? "positive" : "warning"}>{item.status}</Badge><code>{item.manifest_hash.slice(0, 16)}…</code></article>)}</div></section><section className="panel"><div className="section-heading"><div><h2>Upgrade readiness</h2><small>Release and self-recovery preflight</small></div><button type="button" className="button" disabled={busy !== null} onClick={checkReadiness}>{busy === "readiness" ? "Checking…" : "Run checks"}</button></div>{readiness ? <><Badge tone={readiness.ready ? "positive" : "negative"}>{readiness.ready ? "ready" : "blocked"}</Badge><div className="readiness-list">{readiness.checks.map((check) => <article key={check.check_id}><Badge tone={check.status === "pass" ? "positive" : check.status === "fail" ? "negative" : "warning"}>{check.status}</Badge><div><strong>{check.title}</strong><small>{check.explanation}</small></div></article>)}</div></> : <p className="muted">Run readiness checks before upgrade or disaster-recovery operations.</p>}</section></section>}
  </main>;
}
