{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeops.fullname" . }}-artifacts
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.artifactSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeops.fullname" . }}-backups
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backupSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeops.fullname" . }}-operations
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.operationSize }}
{{- end }}
